# NUMPY LIBRARY

**Numpy arrays come in two flavors **  

1. **Vectors:** strictly 1D arrays  
2. **Matrices:** 2-dimensional  
    - Should note a matrix can still have only one row or one column  
    - Denoted by double brackets
    
**Why you want to convert Python lists to NumPy arrays:  **
- More compact than python lists (less memory)
- More efficient  
- More convenient with vector and matrix operations/computing  
- Built in functions (statistics, histograms,etc)
- Speed
    
### Creating Arrays by Casting a List

In [1]:
# Create list
my_list = [1,2,3]

# Cast python list to 1 dimensional numpy array
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [2]:
# Create list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

# Cast list of lists to a two dimensional array.Two sets of brackets indicate this is a two dimensional array.
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# More common way to quickly geneate an array, similar to python's range function
np.arange(0,10,2) # Third argumnt is the step size

array([0, 2, 4, 6, 8])

In [4]:
# Generate array of all zeros
np.zeros(3)

array([0., 0., 0.])

In [5]:
# Generate two dimensional matrix using tuples
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Linspace uses third argument as the number of points you want
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
# Create identify matrix.two dimensional square matrix, number of rows is the same as number of columns and diagonal of ones. useful for linear algebra problems
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Creating Arrays with Built-In Rand Functions

In [8]:
# Create one dimensional array of random numbers from a uniform distribution 0 to 1
np.random.rand(5)

array([0.97901092, 0.08601375, 0.79683366, 0.35093512, 0.47632356])

In [9]:
# Create 5x5 matrix of random numbers from a uniform distribution 0 to 1
np.random.rand(5,5)

array([[0.33067437, 0.68629033, 0.68058831, 0.09918123, 0.42859679],
       [0.72085395, 0.38122092, 0.47514971, 0.97126748, 0.20856237],
       [0.65583361, 0.27083205, 0.0549666 , 0.99798003, 0.20471486],
       [0.5936843 , 0.17757701, 0.81726924, 0.69129267, 0.38406812],
       [0.40442385, 0.16704636, 0.17930161, 0.26406598, 0.05009449]])

In [10]:
# Create array of random numbers from a stardard normal distribution centered around 0
np.random.randn(2)

array([1.37792653, 1.2373882 ])

In [11]:
# Create array of random numbers from a stardard normal distribution centered around 0
np.random.randn(4,4)

array([[-0.39454264, -0.01979572,  1.09287719,  0.92541874],
       [-1.77970471, -0.71263283,  0.97212732, -0.68215587],
       [-0.0518899 , -0.36139114,  0.30226186,  0.23311679],
       [ 0.24110024, -0.08489747,  0.4589805 ,  0.0937202 ]])

In [12]:
# Create array of random integers from a low number (inclusive) to high number (exclusive)
np.random.randint(1,100,10) #3rd argument is the particular number of random integers you want 

array([83, 49, 77, 76, 97, 58, 56, 57, 69, 94])

### Useful Array Methods

In [13]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 5, 39,  5, 31, 41,  5, 47, 10, 23, 23])

In [15]:
# Reshape array to 5 x 5 matrix
arr.reshape(5,5)# pass in new dimensions, # rows and # columns, you want

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
# Find max
ranarr.max()

47

In [17]:
# Fin min value
ranarr.min()

5

In [18]:
# Find location value of max
ranarr.argmax()

6

In [19]:
# Find location of min
ranarr.argmin()

0

### Attributes
When calling attributes, do not need parenthesis

In [20]:
arr.shape

(25,)

In [21]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [22]:
# Find data type of array
arr.dtype

dtype('int64')

In [23]:
from numpy.random import randint
randint(2,10)

7

### Indexing and Selection

In [24]:
# Create an array of 11 elements from 0 to 10
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Return value at index 8
arr[8]

8

In [26]:
# Use slicing
arr[1:5] # return all values from start index all the way up to (but not including) stop index

array([1, 2, 3, 4])

In [27]:
# Slice everything before index 6
arr[:6] #same as [0:6], w slice notation grab one more than you actually need

array([0, 1, 2, 3, 4, 5])

In [28]:
# Everything beyond index 5
arr[5:] 

array([ 5,  6,  7,  8,  9, 10])

In [29]:
# Broadcast value to first 5 digits
arr[0:5] = 100

In [30]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
# Create copy of an array
arr_copy = arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

### Indexing 2D Array (Matrices)

In [32]:
import numpy as np
arr_2d = np.array([[5,10,15],[20,25,30],[30,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [33]:
# Double bracket format to grab elements from 2D array (matrix)
arr_2d[2][1] # , row index, column index


40

In [34]:
# Single bracket with comma notation to grab elements from 2D array, recommended way!
arr_2d[2,1]

40

In [35]:
# Grab top right corner
arr_2d[:2,1:] 

array([[10, 15],
       [25, 30]])

### Conditional Selection

In [36]:
arr = np.arange(1,11)

In [37]:
# Create boolean array using comparison operator
bool_arr =arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
# Use boolean array to index (conditionally select) elements of the original array where the boolean array was true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [39]:
# One step conditional selection
arr[arr<3]

array([1, 2])

In [40]:
# Create 2D matrix of 50 integers starting at 0
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2d[1:3,] # Stop index, grab one more than you actually need

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# **Basic Operations**

### ** Array with Array**

In [42]:
import numpy as np

# Create array of 11 digits from 0 to 10
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Add two arrays together on an element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### **Array with Scalers (Single Numbers)**

In [44]:
# Add 100 to every element in the array
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

 ### Universal Array Functions


In [45]:
# Take square root of every element in the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [46]:
# Find exponents
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [47]:
# Find max
np.max(arr)

10

# **EXERCISES**

In [48]:
# Import NumPy as np
import numpy as np

In [49]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
# Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
# Create an array of 10 fives
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [52]:
# Create an array of 10 fives
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [53]:
# Create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [54]:
# Create an array of even integers from 10 to 50
np.arange(10,51,2) # remember third argument sets the step

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [55]:
# Create a 3x3 matrix with values from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# Generate random number between 0 and 1
np.random.rand(1)

array([0.83113515])

In [58]:
# Generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([-0.11353966, -0.47034244,  0.6590702 , -1.15240268,  0.26488398,
        1.43220142,  1.78242659,  0.34561869, -0.01601281, -0.27675708,
       -0.13966512, -0.13058413,  0.08757828,  0.83558796, -0.53862717,
       -0.36037033,  0.16292894, -1.46879534,  2.62600689, -1.69713875,
       -0.50790829,  0.42547754,  0.91044377,  1.23426653,  0.61570344])

In [59]:
# Generate matrix
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [60]:
# Generate matrix
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [61]:
# Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [62]:
# Create outputs
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
# Select bottom right corner
mat[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [64]:
# Select the 20
mat[3,4]

20

In [65]:
# Grab chunk and create 3x1 matrix output with double brackets
mat[:3,1:2] # Slice everything up to but not including column index 2

array([[ 2],
       [ 7],
       [12]])

In [66]:
# Go to index 4 row and return everything
mat[4,:]

array([21, 22, 23, 24, 25])

In [67]:
# Return last row with negative indexing
mat[-1,:]

array([21, 22, 23, 24, 25])

In [68]:
# Grab all the columns of the last two rows with double bracket notation output
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
# Get sum of all the values in mat using universal function
mat.sum()

325

In [70]:
# Get sum of all the values in mat using sum function
np.sum(mat)

325

In [71]:
# Get standard deviation of the values in mat using universal function
mat.std()

7.211102550927978

In [72]:
# Get standard deviation of the values in mat using standard deviation function
np.std(mat)

7.211102550927978

In [73]:
# Get sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])